/*
 * This source file was generated by the Gradle 'init' task
 */
package com.spectorstudios;

public class App {
  public String getGreeting() {
    return "Hello Monkey!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    App test = new App();
    System.out.println(test.getGreeting());
  }
}
