/*
 * This source file was generated by the Gradle 'init' task
 * */

package com.spectorstudios;

public class Lexer {

  public String input;
  public int position;
  public int readPosition;
  public String ch;

  Lexer(String input){
    this.input = input;
    this.readChar();
  }

  public void readChar(){
    if (this.readPosition >= this.input.length()) {
      this.ch = null;
    } else {
      this.position = this.readPosition;
      this.readPosition += 1;
    }
  }

  public Token NewToken() {
    Token tok;
    
    switch (this.ch) {
      case "=":
        tok = new Token(Token.ASSIGN, this.ch);
        break;

      default:
        return null;
    }

    return tok;
  }
}
