/*
 * This source file was generated by the Gradle 'init' task
 */
package com.spectorstudios;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAScanner() {
        //App classUnderTest = new App();
        assertNotNull(App.scanner, "app should have a scanner");
    }
}
