
/*
 * This source file was generated by the Gradle 'init' task 
 */

package com.spectorstudios.tokens;

public enum TokenType {

  // Special
  ILLEGAL("ILLEGAL"),
  EOF("EOF"),

  // Identifiers and numberrs
  IDENT("IDENT"),
  INT("INT"),

  // Operators
  ASSIGN("="),
  PLUS("+"),
  MINUS("-"),
  ASTERISK("*"),
  SLASH("/"),

  BANG("!"),
  LT("<"),
  GT(">"),

  EQ("=="),
  NOT_EQ("!="),
  //TODO Add <= and >= and support for it

  // Delimiters
  COMMA(","),
  SEMICOLON(";"),

  LPAREN("("),
  RPAREN(")"),

  LBRACE("{"),
  RBRACE("}"),

  // Keywords
  FUNCTION("FUNCTION"),
  LET("LET"),
  TRUE("TRUE"),
  FALSE("FALSE"),
  IF("IF"),
  ELSE("ELSE"),
  RETURN("RETURN");

  private final String prettyString;

  TokenType(String prettyString) {
    this.prettyString = prettyString;
  }

  @Override
  public String toString() {
    return prettyString;
  }
}
